## Libraries ----
library("dplyr")
library("rvest")
library("stringr")
library("jsonlite")

## Init ----
base_url = "http://docs.ggplot2.org/current/"

webpage = html(base_url)

link_nodes = webpage %>% html_nodes("a")

# links = lapply(link_nodes, function(n) {
#   # URL
#   link = html_attr(n, "href")
#   full_link = paste0(base_url, link)
#
#   # What does it link to?
#   name = full_link %>% tools::file_path_sans_ext() %>% basename()
#
#   if (name == "#" | str_detect(link, "^http"))
#     is_doclink = FALSE
#   else
#     is_doclink = TRUE
#
#   c(url = full_link, name = name, is_doclink = is_doclink)
# })

links <- list()
for (i in 1:length(link_nodes)) {
  # HTML node
  node = link_nodes[[i]]

  # Link metadata
  # None of the doc links are preceded by "http" so we filter those out.
  # We also need to do some manual removal of faulty links, like "index.html".
  link = html_attr(node, "href")
  is_doclink = (!str_detect(link, "^http") & !link %in% c("#", "index.html"))
  if (is_doclink) {
    full_link = paste0(base_url, link)
  } else {
    full_link = link
  }

  name = full_link %>% tools::file_path_sans_ext() %>% basename()
  if (is_doclink) {
    doctype = name %>% str_extract(perl("[a-z]*(?=_)"))

    # Some pages only document data, so we don't need to follow their links
    if (is.na(doctype)) {
      doctype = "data"
    }
  } else {
    doctype = "external"
  }



  # Follow doclinks and find: args, aesthetics
  # The docpages are generated by a machine and thus are very similar.
  if (is_doclink) {
    if (doctype != "data") {
      docpage = html(full_link)

      # Get arguments
      args_node = docpage %>%
        html_node("dl")
      if (!is.null(args_node)) {
        args = args_node %>%
          html_nodes("dt") %>%
          html_text()

        args = args[!args %in% "..."]
      } else {
        args = NULL
      }

      # Some docpages do not list available aesthetics
      aesthetics_node = docpage %>%
        html_node(".Aesthetics")
      if (!is.null(aesthetics_node)) {
        aesthetics = aesthetics_node %>%
          html_nodes("code") %>%
          html_text()
      } else {
        aesthetics = NULL
      }
    } else {
      args = NULL
      aesthetics = NULL
    }
  } else {
    args = NULL
    aesthetics = NULL
  }


  # Define datalist
  link_data = list()
  link_data[['url']] = full_link
  link_data[['is_doclink']] = is_doclink
  # link_data[['name']] = name
  link_data[['doctype']] = doctype
  link_data[['args']] = args
  link_data[['aesthetics']] = aesthetics

  # Return list
  links[[doctype]]
  links[[doctype]][[name]] = link_data
}


# Write to JSON
json <- jsonlite::toJSON(
  links,
  pretty = TRUE
)

cat(json, file="frontend/data/ggplot_docs.json")
